<script setup lang="ts">
import { Bell, Check } from 'lucide-vue-next';
import EmptyState from '../../components/EmptyState.vue';
import StatePanel from '../../components/StatePanel.vue';
import { useResource } from '../../composables/useResource';
import { api } from '../../lib/api';
import { formatDateTime } from '../../lib/format';
interface NotificationItem{id:string;title:string;message:string;readAt:string|null;createdAt:string;actionUrl:string|null}
const notifications=useResource(()=>api.get<NotificationItem[]>('/notifications'));
async function markRead(item:NotificationItem){if(item.readAt)return;await api.post(`/notifications/${item.id}/read`);item.readAt=new Date().toISOString()}
</script>
<template><div class="portal-page"><header><span class="eyebrow">Pembaruan penting</span><h1>Notifikasi</h1><p>Atur frekuensi dan kanal di pengaturan agar notifikasi tetap membantu, bukan mengganggu.</p></header><StatePanel v-if="notifications.loading.value" state="loading"/><StatePanel v-else-if="notifications.error.value" state="error" :message="notifications.error.value" @retry="notifications.reload"/><EmptyState v-else-if="!notifications.data.value?.length" title="Tidak ada notifikasi"/><div v-else class="items"><article v-for="item in notifications.data.value" :key="item.id" class="card card-body" :class="{unread:!item.readAt}"><span><Bell v-if="!item.readAt" :size="18"/><Check v-else :size="18"/></span><div><h2>{{ item.title }}</h2><p>{{ item.message }}</p><small>{{ formatDateTime(item.createdAt) }}</small><div class="notification-actions"><a v-if="item.actionUrl" :href="item.actionUrl">Buka detail</a><button v-if="!item.readAt" type="button" @click="markRead(item)">Tandai dibaca</button></div></div><i v-if="!item.readAt" aria-label="Belum dibaca"/></article></div></div></template>
<style scoped>.portal-page{display:grid;max-width:78rem;gap:1.2rem;margin-inline:auto}header h1{margin-bottom:.45rem;font-size:clamp(2rem,4.5vw,3rem)}header p{color:var(--ink-650)}.items{display:grid;gap:.6rem}.items article{position:relative;display:flex;gap:.8rem}.items article.unread{border-left:3px solid var(--teal-600)}.items article>span{display:grid;width:2.4rem;height:2.4rem;flex:none;place-items:center;border-radius:50%;background:var(--teal-100);color:var(--teal-700)}h2{margin-bottom:.2rem;font-size:1rem}p{margin-bottom:.2rem;color:var(--ink-650)}small{color:var(--ink-500)}i{position:absolute;top:1rem;right:1rem;width:.5rem;height:.5rem;border-radius:50%;background:var(--teal-600)}.notification-actions{display:flex;gap:.8rem;margin-top:.45rem}.notification-actions a,.notification-actions button{padding:0;border:0;background:transparent;color:var(--teal-700);font-size:.75rem;font-weight:800;text-decoration:none;cursor:pointer}</style>
