<script setup lang="ts">
import { CheckCircle2, MoonStar } from 'lucide-vue-next';
import { onMounted, reactive, ref } from 'vue';
import StatePanel from '../../components/StatePanel.vue';
import { api, ApiClientError } from '../../lib/api';

type Digest = 'IMMEDIATE' | 'DAILY' | 'EMERGENCY_ONLY';
interface NotificationPreferences { inApp: boolean; email: boolean; quietHoursStart: string | null; quietHoursEnd: string | null; digest: Digest }
const saved=ref(false);const loading=ref(true);const busy=ref(false);const error=ref('');
const preferences=reactive({email:true,inApp:true,digest:'IMMEDIATE' as Digest,quietStart:'',quietEnd:''});
async function load(){loading.value=true;error.value='';try{const value=await api.get<NotificationPreferences>('/notification-preferences');preferences.email=value.email;preferences.inApp=value.inApp;preferences.digest=value.digest;preferences.quietStart=value.quietHoursStart??'';preferences.quietEnd=value.quietHoursEnd??''}catch(cause){error.value=cause instanceof ApiClientError||cause instanceof Error?cause.message:'Preferensi belum dapat dimuat.'}finally{loading.value=false}}
async function save(){busy.value=true;saved.value=false;error.value='';try{await api.put('/notification-preferences',{inApp:preferences.inApp,email:preferences.email,quietHoursStart:preferences.quietStart||null,quietHoursEnd:preferences.quietEnd||null,digest:preferences.digest});saved.value=true}catch(cause){error.value=cause instanceof ApiClientError||cause instanceof Error?cause.message:'Preferensi belum dapat disimpan.'}finally{busy.value=false}}
onMounted(load);
</script>
<template><div class="portal-page"><header><span class="eyebrow">Kendali ada pada Anda</span><h1>Pengaturan notifikasi</h1><p>Pilih informasi yang berguna dan waktu yang nyaman untuk menerimanya.</p></header><StatePanel v-if="loading" state="loading"/><StatePanel v-else-if="error" state="error" :message="error" @retry="load"/><form v-else class="card card-body form-grid" @submit.prevent="save"><fieldset><legend>Kanal notifikasi</legend><label><input v-model="preferences.inApp" type="checkbox"/> Notifikasi di WargaHub</label><label><input v-model="preferences.email" type="checkbox"/> Email</label><div class="field"><label for="notification-digest">Frekuensi ringkasan</label><select id="notification-digest" v-model="preferences.digest"><option value="IMMEDIATE">Segera</option><option value="DAILY">Ringkasan harian</option><option value="EMERGENCY_ONLY">Hanya keadaan darurat</option></select></div></fieldset><fieldset><legend><MoonStar :size="18"/> Jam tenang</legend><div class="two-fields"><div class="field"><label for="quiet-start">Mulai</label><input id="quiet-start" v-model="preferences.quietStart" type="time"/></div><div class="field"><label for="quiet-end">Selesai</label><input id="quiet-end" v-model="preferences.quietEnd" type="time"/></div></div><p class="muted small">Informasi darurat dapat melewati jam tenang sesuai kebijakan keselamatan organisasi.</p></fieldset><div v-if="saved" class="notice" role="status"><CheckCircle2 :size="18"/> Preferensi tersimpan.</div><button class="button" type="submit" :disabled="busy">{{ busy?'Menyimpan…':'Simpan pengaturan' }}</button></form></div></template>
<style scoped>.portal-page{display:grid;max-width:78rem;gap:1.2rem;margin-inline:auto}header h1{margin-bottom:.45rem;font-size:clamp(2rem,4.5vw,3rem)}header p{color:var(--ink-650)}fieldset{display:grid;gap:.65rem;padding:1rem;border:1px solid var(--line);border-radius:var(--radius-md)}legend{display:inline-flex;align-items:center;gap:.4rem;padding-inline:.35rem;font-weight:850}fieldset>label{display:flex;align-items:center;gap:.55rem;min-height:2.75rem}input[type=checkbox]{width:1.1rem;height:1.1rem;accent-color:var(--teal-700)}.two-fields{display:grid;grid-template-columns:1fr 1fr;gap:.7rem}@media(max-width:480px){.two-fields{grid-template-columns:1fr}}</style>
